# Generated by Django 6.0.6 on 2026-07-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'ordering': ['-is_main', 'id']},
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
