# Generated by Django 6.0.6 on 2026-07-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_serviceimage_options_serviceimage_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('TUYXONA', "To'yxona"), ('FOTO_VIDEO', 'Foto va Video'), ('XONANDA', 'Xonanda va Musiqa'), ('SALON', "To'y salonlari"), ('KORTEJ', 'Kortej xizmati'), ('TASHKILOTCHI', "To'y tashkilotchilari"), ('LIBOSLAR', 'Liboslar'), ('AKSESSUARLAR', 'Aksessuarlar')], max_length=20),
        ),
    ]
